### ISSUE TITLE
User Management - KendoGrid Enum Filter component

### ISSUE THREAD

**Issue by ruslan-sh** [ruslan-sh/react-onboarding-practice-course#9]

**Comment by ruslan-sh** [comment]
![image](https://user-images.githubusercontent.com/7404779/59913527-f3b37700-9420-11e9-8a62-ab5d6c64df8f.png)

**Comment by xarety** [comment]
existing filter: `singleItemMultiSelectColumnMenuFilter`/`multiItemMultiSelectColumnMenuFilter`
